### ISSUE TITLE
Trunking new version

### ISSUE THREAD

**Issue by AlirezaSN** [itips/Iran-Onesignal-iOS#1]
Hi there,
Looks like You missed trunking new version (2.11) to Cocoapods, because it installs version 2.9.4.1.
i attached the `pod install` command log screenshot.
Thanks.

<img width="397" alt="Screen Shot 1399-01-26 at 15 12 18" src="https://user-images.githubusercontent.com/11287106/79216472-756a0a80-7e62-11ea-88fd-11e5a5dd1230.png">

**Comment by h-o-sein** [comment]
> Hi there,
> 
> Looks like You missed trunking new version (2.11) to Cocoapods, because it installs version 2.9.4.1.
> 
> i attached the `pod install` command log screenshot.
> 
> Thanks.
> 
> 
> 
> <img width="397" alt="Screen Shot 1399-01-26 at 15 12 18" src="https://user-images.githubusercontent.com/11287106/79216472-756a0a80-7e62-11ea-88fd-11e5a5dd1230.png">
> 
> 

Hi
It will be updated soon.😊

**Comment by h-o-sein** [comment]
Hi
Pod Updated
